### PR TITLE
fix: Use the right start/finish icons based on the type;

### LINKED ISSUE #88: Icon Error in Integrations.tsx
I have an integration that uses an extension. I was getting an error in the `render` method on either the `startConnectionIcon` or `finishConnectionIcon` being undefined (I think it was the finish icon).

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #88

Ported over the logic from [here](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/common/icon-path.pipe.ts) and [here](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/integration-actions-provider.service.ts#L305-L315) *kind of*, which fixes the icon display in the app when it's pointed at staging.  Also re-synced the icon assets as most connectors now provide their icon from the backend.

image

TODO
 * [x] comments and tidying
 * [x] tests
 * [x] feedback welcome!

### CODE REVIEW

**Comment by riccardo-forina** [comment]
Looks great! Approved but that will be undone if you push new commits, so I did it quite freely :P

**Comment by gashcrumb** [comment]
> Looks great! Approved but that will be automatically undone if you push new commits, so I did it quite freely :P

lol, I'm not done!  But thanks :smile:

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react-poc/471/artifacts/0/home/circleci/project/doc/index.html)

**Comment by gashcrumb** [comment]
@riccardo-forina I'm wondering, would a unit test be good for `getStepIcon` or not, when looking at how a render prop pattern component is tested I'm less sure that a unit test would be a good thing, thoughts?

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react-poc/495/artifacts/0/home/circleci/project/doc/index.html)

**Comment by riccardo-forina** [comment]
`WithIntegrationHelper` has been a great mistake of mine. I wrote it to make it easier to write the 2 methods that have to consume the `Fetch` component and kinda stuck to it for consistency, but it's just wrong. All the helpers exposed by that component should be a plain js module, and consumers of those helpers should just import the ones they require from the module and call it a day.

So instead of this:

```tsx
import { WithIntegrationHelpers } from '@syndesis/api';

...
<WithIntegrationHelpers>
{({ getStepIcon, ... }) => 
   <Something icon={getStepIcon(...)} />
}
</WithIntegrationHelpers>
```

We should simply have:
```tsx
import { getIntegrationStepIcon } from '@syndesis/api';

...
<Something icon={getStepIcon(...)} />
```

Simpler, isn't it? And testable. I haven't done this already only because I'm not sure about those 2 methods that require `Fetch` component. Do you have any suggestion?

All things considered tho, if think we should just do this refactor and if we don't come up with a good idea for the methods that require the `Fetch` component, we could simply keep `WithIntegrationHelpers` but with only those methods; the rest should stay on its own module.

WDYT?

**Comment by gashcrumb** [comment]
> All things considered tho, if think we should just do this refactor and if we don't come up with a good idea for the methods that require the Fetch component, we could simply keep WithIntegrationHelpers but with only those methods; the rest should stay on its own module.

Yeah, that makes perfect sense to do.  And actually we may wind up putting some of the other lifecycle calls for starting/stopping/deleting etc. into WithIntegrationHelpers, as those are calls that would be needed in a few places that will also require the API endpoint etc.

I did need the API URL endpoint for the `getStepIcon` only because in some cases we need a URL that points to some backend location, but I could make that an argument to that function.

**Comment by gashcrumb** [comment]
I can work on that tomorrow BTW :-)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react-poc/504/artifacts/0/home/circleci/project/doc/index.html)

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/533/artifacts/0/home/circleci/project/doc/index.html)

**Comment by gashcrumb** [comment]
Refactored, added a `.prettierrc` too.

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/553/artifacts/0/home/circleci/project/doc/index.html)

**Comment by gashcrumb** [comment]
BTW the refactoring gave me a really nice tour of all the files involved in the editor :laughing:

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/557/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

**Comment by gashcrumb** [comment]
Ok this is done pending feedback, thanks!

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/567/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)

File: app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectActionPage.tsx [hunk 1]
```diff
@@ -72,7 +76,7 @@ export class SelectActionPage extends React.Component {
                       header={<IntegrationCreatorBreadcrumbs step={3} />}
                       sidebar={
                         <WithIntegrationHelpers>
-                          {({ getSteps }) => {
+                          {({}) => {
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectActionPage.tsx]: well this can be nuked now!

File: app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectConnectionPage.tsx [hunk 2]
```diff
@@ -55,7 +59,7 @@ export class SelectConnectionPage extends React.Component {
               header={<IntegrationCreatorBreadcrumbs step={3} />}
               sidebar={
                 <WithIntegrationHelpers>
-                  {({ getSteps }) => {
+                  {({}) => {
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectConnectionPage.tsx]: and this

File: app/ui-react/syndesis/src/modules/integrations/pages/create/configure/editConnection/SelectActionPage.tsx [hunk 3]
```diff
@@ -71,7 +75,7 @@ export class SelectActionPage extends React.Component {
                         header={<IntegrationCreatorBreadcrumbs step={3} />}
                         sidebar={
                           <WithIntegrationHelpers>
-                            {({ getSteps }) => (
+                            {({}) => (
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/create/configure/editConnection/SelectActionPage.tsx]: this too

File: app/ui-react/syndesis/src/modules/integrations/pages/create/configure/main/AddStepPage.tsx [hunk 4]
```diff
@@ -50,7 +50,7 @@ export class AddStepPage extends React.Component {
                     integration as well.
                   </p>
                   <WithIntegrationHelpers>
-                    {({ getSteps }) => (
+                    {({}) => (
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/create/configure/main/AddStepPage.tsx]: +1

File: app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/addConnection/SelectActionPage.tsx [hunk 5]
```diff
@@ -69,7 +73,7 @@ export class SelectActionPage extends React.Component {
                       header={<IntegrationEditorBreadcrumbs step={1} />}
                       sidebar={
                         <WithIntegrationHelpers>
-                          {({ getSteps }) => {
+                          {({}) => {
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/addConnection/SelectActionPage.tsx]: 🍬

File: app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/addConnection/SelectConnectionPage.tsx [hunk 6]
```diff
@@ -54,7 +58,7 @@ export class SelectConnectionPage extends React.Component {
               header={<IntegrationEditorBreadcrumbs step={1} />}
               sidebar={
                 <WithIntegrationHelpers>
-                  {({ getSteps }) => {
+                  {({}) => {
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/addConnection/SelectConnectionPage.tsx]: 🍪

File: app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/editConnection/SelectActionPage.tsx [hunk 7]
```diff
@@ -70,7 +74,7 @@ export class SelectActionPage extends React.Component {
                         header={<IntegrationEditorBreadcrumbs step={1} />}
                         sidebar={
                           <WithIntegrationHelpers>
-                            {({ getSteps }) => (
+                            {({}) => (
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/editConnection/SelectActionPage.tsx]: 🚌

File: app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/main/AddStepPage.tsx [hunk 8]
```diff
@@ -53,7 +53,7 @@ export class AddStepPage extends React.Component {
                     integration as well.
                   </p>
                   <WithIntegrationHelpers>
-                    {({ getSteps }) => (
+                    {({}) => (
```
Comment (riccardo-forina) [inline app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/main/AddStepPage.tsx]: 🐖

File: app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectActionPage.tsx (hunk 1 above)
Comment (gashcrumb) [reply app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectActionPage.tsx]: well, lemme get on that :-)  and all those others

Comment (gashcrumb) [reply app/ui-react/syndesis/src/modules/integrations/pages/create/configure/addConnection/SelectActionPage.tsx]: right, so even `WithIntegrationHelpers` isn't needed in these cases, of course silly me...

**Comment by gashcrumb** [comment]
Drastically reduced the references to integration helpers, I left the one on the list page though, that'll eventually get the start/stop functions when I get 'em in there.  Thanks!

**Comment by riccardo-forina** [comment]
PR Storybook available [here](https://circleci.com/api/v1.1/project/github/syndesisio/syndesis-react/585/artifacts/0/home/circleci/repo/app/ui-react/doc/index.html)
